# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('projectcode', models.CharField(max_length=10, unique=True)),
                ('omschrijving', models.CharField(max_length=80)),
                ('geschatte_omzet', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('werkelijke_omzet', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('einddatum_project', models.DateTimeField()),
                ('broncampagne', models.CharField(blank=True, max_length=80, null=True)),
                ('onenote_doc', models.URLField(blank=True, null=True)),
                ('actief', models.BooleanField(default=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf')),
                ('klantpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_Klantpartner', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('opdrachtgever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Orderstadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('orderstadium', models.CharField(max_length=30, unique=True)),
                ('order', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name_plural': 'Orderstadia',
            },
        ),
        migrations.CreateModel(
            name='Verkoopkans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('projectcode', models.CharField(max_length=10, unique=True)),
                ('omschrijving', models.CharField(max_length=80)),
                ('geschatte_omzet', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('werkelijke_omzet', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('einddatum_project', models.DateTimeField()),
                ('broncampagne', models.CharField(blank=True, max_length=80, null=True)),
                ('onenote_doc', models.URLField(blank=True, null=True)),
                ('actief', models.BooleanField(default=True)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf')),
                ('klantpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_Klantpartner', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('opdrachtgever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon')),
            ],
            options={
                'verbose_name_plural': 'Verkoopkansen',
            },
        ),
        migrations.CreateModel(
            name='Verkoopstadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('verkoopstadium', models.CharField(max_length=30, unique=True)),
                ('verkoopkans', models.DecimalField(decimal_places=2, max_digits=4)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name_plural': 'Verkoopstadia',
                'ordering': ['verkoopkans'],
            },
        ),
        migrations.AddField(
            model_name='verkoopkans',
            name='verkoopstadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Verkoop_Stadium', to='projecten.Verkoopstadium'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderstadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Stadium', to='projecten.Orderstadium'),
        ),
    ]
