# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verkoopkans',
            name='startdatum_project',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='einddatum_project',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
