# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0002_auto_20171004_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Orders',
                'proxy': True,
                'indexes': [],
            },
            bases=('projecten.verkoopkans',),
        ),
        migrations.AlterModelOptions(
            name='verkoopkans',
            options={'ordering': ['-modified_dt'], 'verbose_name_plural': 'Verkoopkansen'},
        ),
        migrations.AlterField(
            model_name='order',
            name='einddatum_project',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='einddatum_project',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='startdatum_project',
            field=models.DateField(blank=True, null=True),
        ),
    ]
