# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0005_auto_20171207_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='projectcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='projectcode',
            field=models.CharField(max_length=10),
        ),
    ]
