# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projecten', '0007_auto_20171207_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstadium',
            options={'ordering': ['orderstadium'], 'verbose_name_plural': 'Orderstadia'},
        ),
        migrations.AlterModelOptions(
            name='verkoopstadium',
            options={'ordering': ['verkoopstadium'], 'verbose_name_plural': 'Verkoopstadia'},
        ),
        migrations.RemoveField(
            model_name='verkoopkans',
            name='broncampagne',
        ),
        migrations.RemoveField(
            model_name='verkoopkans',
            name='geschatte_omzet',
        ),
        migrations.RemoveField(
            model_name='verkoopkans',
            name='werkelijke_omzet',
        ),
        migrations.AddField(
            model_name='verkoopkans',
            name='ordereigenaar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_Ordereigenaar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verkoopkans',
            name='productgroep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_Productgroep', to='producten.Productgroep'),
        ),
    ]
