# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20171207_1232'),
        ('projecten', '0009_auto_20180329_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kwo_ontvanger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_KWO_Ontvanger', to='crm.Contactpersoon'),
        ),
        migrations.AddField(
            model_name='verkoopkans',
            name='kwo_ontvanger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_KWO_Ontvanger', to='crm.Contactpersoon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='opdrachtgever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_Opdrachtgever', to='crm.Contactpersoon'),
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='opdrachtgever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_Opdrachtgever', to='crm.Contactpersoon'),
        ),
    ]
