# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projecten', '0010_auto_20180418_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omzetpermaand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('jaar', models.IntegerField(choices=[(1, '2018'), (2, '2019'), (3, '2020'), (4, '2021'), (5, '2022'), (6, '2023'), (7, '2024'), (8, '2025'), (9, '2026'), (10, '2027')])),
                ('maand', models.IntegerField(choices=[(1, 'Januarie'), (2, 'Februari'), (3, 'Maart'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'July'), (8, 'Augustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'December')])),
                ('omzet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('projectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Omzetpermaand_Verkoopkans', to='projecten.Verkoopkans')),
            ],
            options={
                'verbose_name_plural': 'Omzetten per maand',
                'ordering': ['-modified_dt'],
            },
        ),
    ]
