# Generated by Django 2.0.4 on 2018-06-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0002_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_auto_20180606_1408'),
        ('projecten', '0012_auto_20180606_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingregistratie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('bijzonderheden', models.CharField(blank=True, max_length=512, null=True)),
                ('datum', models.DateField()),
                ('contactpersoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon')),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name_plural': 'Trainingsregistraties',
                'ordering': ['training', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='verkoopkans',
            name='klantpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verkoopkans_Klantpartner', to=settings.AUTH_USER_MODEL, verbose_name='Leadeigenaar'),
        ),
        migrations.AddField(
            model_name='trainingregistratie',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projecten.Verkoopkans'),
        ),
        migrations.AddField(
            model_name='trainingregistratie',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingregistratie',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producten.Training'),
        ),
    ]
