# Generated by Django 2.0.4 on 2019-11-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0013_auto_20180606_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verkoopkans',
            options={'ordering': ['projectcode'], 'verbose_name_plural': 'Verkoopkansen'},
        ),
    ]
