# Generated by Django 2.0.4 on 2019-08-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projecten.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projecten', '0014_auto_20180703_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urenpermedewerker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('jaar', models.IntegerField(choices=[(1, '2018'), (2, '2019'), (3, '2020'), (4, '2021'), (5, '2022'), (6, '2023'), (7, '2024'), (8, '2025'), (9, '2026'), (10, '2027')])),
                ('week', models.IntegerField(validators=[projecten.models.validate_weken])),
                ('uren', models.PositiveSmallIntegerField()),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('projectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Urenpermedewerker_Order', to='projecten.Verkoopkans')),
            ],
            options={
                'verbose_name_plural': 'Uren per medewerker',
                'ordering': ['jaar', 'week'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='urenpermedewerker',
            unique_together={('projectcode', 'jaar', 'week')},
        ),
    ]
