# Generated by Django 2.0.4 on 2019-08-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projecten', '0015_auto_20190829_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urenpermedewerker',
            options={'ordering': ['medewerker', 'jaar', 'week'], 'verbose_name_plural': 'Uren per medewerker'},
        ),
        migrations.AddField(
            model_name='urenpermedewerker',
            name='medewerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medewerker_Order', to=settings.AUTH_USER_MODEL),
        ),
    ]
