# Generated by Django 2.0.4 on 2019-12-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0003_product'),
        ('projecten', '0015_auto_20191128_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='urenpermedewerker',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medewerker_Order_Product', to='producten.Product'),
        ),
    ]
