# Generated by Django 2.0.4 on 2019-12-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producten', '0003_product'),
        ('projecten', '0016_urenpermedewerker_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderregel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('aantal_eenheden', models.IntegerField(verbose_name='Aantal Eenheden')),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producten.Product')),
                ('projectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orderregel_Verkoopkans', to='projecten.Verkoopkans')),
            ],
            options={
                'verbose_name': 'Orderregel',
                'verbose_name_plural': 'Orderregels',
            },
        ),
    ]
