# Generated by Django 2.0.4 on 2019-08-29 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projecten', '0016_auto_20190829_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='urenpermedewerker',
            unique_together={('medewerker', 'projectcode', 'jaar', 'week')},
        ),
    ]
