# Generated by Django 2.0.4 on 2019-12-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0014_auto_20180703_1404'),
        ('projecten', '0018_auto_20191205_1156'),
    ]

    operations = [
    ]
