# Generated by Django 2.0.4 on 2019-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecten', '0019_merge_20191211_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderregel',
            name='regel_totaal_prijs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Regel totaalprijs'),
        ),
        migrations.AlterField(
            model_name='orderregel',
            name='list_prijs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Listprijs per eenheid'),
        ),
        migrations.AlterField(
            model_name='orderregel',
            name='selling_prijs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sellingprijs per eenheid'),
        ),
    ]
