# Generated by Django 2.0.4 on 2019-12-16 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producten', '0003_product'),
        ('projecten', '0020_auto_20191211_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='urenpermedewerker',
            unique_together={('medewerker', 'projectcode', 'product', 'jaar', 'maand')},
        ),
    ]
