# Generated by Django 2.0.4 on 2020-01-06 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0004_marketinguiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_auto_20190604_0936'),
        ('projecten', '0021_auto_20191216_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketingregistratie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('bijzonderheden', models.CharField(blank=True, max_length=512, null=True)),
                ('datum', models.DateField()),
                ('contactpersoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon')),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('marketinguiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producten.Marketinguiting')),
            ],
            options={
                'verbose_name_plural': 'Marketingregistraties',
                'ordering': ['marketinguiting', 'contactpersoon'],
            },
        ),
    ]
