# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 16:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.TextField()),
                ('datumUitgevoerd', models.DateField(default=datetime.date.today, verbose_name='Datum')),
            ],
            options={
                'verbose_name_plural': 'Activiteiten',
            },
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activiteit statussen',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activiteit typen',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('slug', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('onderwerp', models.CharField(max_length=64)),
                ('omschrijving', models.TextField()),
                ('datumMelding', models.DateField(default=datetime.date.today, verbose_name='Datum melding')),
                ('datumGereed', models.DateField(blank=True, null=True, verbose_name='Datum gereed')),
                ('klant', models.CharField(max_length=64, null=True)),
                ('contactpersoon', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Case statussen',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.CaseStatus'),
        ),
        migrations.AddField(
            model_name='cases',
            name='uitvoerende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='activiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ActivityType'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='caseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Cases'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ActivityStatus'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='uitvoerende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
