# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 15:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.TextField()),
                ('datumUitgevoerd', models.DateField(default=datetime.date.today, verbose_name='Datum')),
            ],
            options={
                'verbose_name_plural': 'Activiteiten',
            },
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activiteit statussen',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activiteit typen',
            },
        ),
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(max_length=64)),
                ('telefoon', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('primair_contact', models.CharField(max_length=64)),
                ('klantpartner', models.CharField(max_length=254)),
                ('emailadres', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Bedrijven',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onderwerp', models.CharField(max_length=64)),
                ('omschrijving', models.TextField()),
                ('datumMelding', models.DateField(default=datetime.date.today, verbose_name='Datum melding')),
                ('datumGereed', models.DateField(blank=True, null=True, verbose_name='Datum gereed')),
                ('klant', models.CharField(max_length=64, null=True)),
                ('contactpersoon', models.CharField(blank=True, max_length=64, null=True)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf')),
            ],
            options={
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Case statussen',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Case typen',
            },
        ),
        migrations.CreateModel(
            name='Contactpersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactnaam', models.CharField(max_length=64)),
                ('functie', models.CharField(max_length=64)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('mobielnummer', models.CharField(max_length=20)),
                ('emailadres', models.CharField(max_length=254)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf')),
            ],
            options={
                'verbose_name_plural': 'Contactpersonen',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcode', models.CharField(max_length=6)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('klantpartner', models.CharField(max_length=254)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf')),
            ],
            options={
                'verbose_name_plural': 'Contracten',
            },
        ),
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leveranciernaam', models.CharField(max_length=64)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('emailadres', models.CharField(max_length=254)),
                ('klantpartner', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Leveranciers',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=64)),
                ('classificatie', models.CharField(max_length=20)),
                ('bevestiging', models.IntegerField()),
                ('oplossingsplan', models.IntegerField()),
                ('workaround', models.IntegerField()),
                ('oplossing', models.IntegerField()),
                ('leverancier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Leverancier')),
            ],
            options={
                'verbose_name_plural': 'SLA-s',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_bij',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Leverancier'),
        ),
        migrations.AddField(
            model_name='cases',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Contactpersoon'),
        ),
        migrations.AddField(
            model_name='cases',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Contract'),
        ),
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.CaseStatus'),
        ),
        migrations.AddField(
            model_name='cases',
            name='uitvoerende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='activiteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ActivityType'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='caseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Cases'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ActivityStatus'),
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='uitvoerende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
