# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name_plural': 'Case typen',
            },
        ),
    ]
