# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activiteiten',
            old_name='caseId',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='activiteiten',
            old_name='datumUitgevoerd',
            new_name='datum_uitgevoerd',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='datumGereed',
            new_name='datum_gereed',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='datumMelding',
            new_name='datum_melding',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='contactpersoon',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='klant',
        ),
        migrations.AddField(
            model_name='cases',
            name='case_code',
            field=models.CharField(default=1, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
