# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170307_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteiten',
            name='tijdsduur',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
