# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_casetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(max_length=64)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('primair_contact', models.CharField(max_length=64)),
                ('klantpartner', models.CharField(max_length=254)),
                ('emailadres', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Bedrijven',
            },
        ),
        migrations.CreateModel(
            name='Contactpersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactnaam', models.CharField(max_length=64)),
                ('functie', models.CharField(max_length=64)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('mobielnummer', models.CharField(max_length=20)),
                ('emailadres', models.CharField(max_length=254)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf')),
            ],
            options={
                'verbose_name_plural': 'Contactpersonen',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcode', models.CharField(max_length=6)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('klantpartner', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contracten',
            },
        ),
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leveranciernaam', models.CharField(max_length=64)),
                ('telefoonnummer', models.CharField(max_length=20)),
                ('emailadres', models.CharField(max_length=254)),
                ('klantpartner', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Leveranciers',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(max_length=64)),
                ('classificatie', models.CharField(max_length=20)),
                ('bevestiging', models.IntegerField()),
                ('oplossingsplan', models.IntegerField()),
                ('workaround', models.IntegerField()),
                ('oplossing', models.IntegerField()),
                ('leverancier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Leverancier')),
            ],
            options={
                'verbose_name_plural': 'SLA-s',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_bij',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Leverancier'),
        ),
        migrations.AddField(
            model_name='cases',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf'),
        ),
        migrations.AddField(
            model_name='cases',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Contactpersoon'),
        ),
        migrations.AddField(
            model_name='cases',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Contract'),
        ),
    ]
