# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20170502_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteiten',
            name='tijdsduur',
        ),
    ]
