# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20170302_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Bedrijf'),
        ),
    ]
