# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 14:29
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_contract_bedrijf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrijf',
            name='telefoon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
