# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20170502_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tijdsduur',
            options={'ordering': ['duration'], 'verbose_name_plural': 'Tijdsduur'},
        ),
        migrations.AddField(
            model_name='tijdsduur',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
