# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20170504_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tijdsduur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuten', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tijdsduur',
                'ordering': ['minuten'],
            },
        ),
        migrations.AddField(
            model_name='activiteiten',
            name='tijdsduur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Tijdsduur'),
        ),
    ]
