# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20170607_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedrijf',
            name='last_modified_user',
        ),
        migrations.RemoveField(
            model_name='contactpersoon',
            name='bedrijf',
        ),
        migrations.RemoveField(
            model_name='contactpersoon',
            name='last_modified_user',
        ),
        migrations.AlterField(
            model_name='cases',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf'),
        ),
        migrations.DeleteModel(
            name='Bedrijf',
        ),
        migrations.DeleteModel(
            name='Contactpersoon',
        ),
    ]
