# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171108_1558'),
        ('support', '0011_auto_20171114_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf'),
        ),
        migrations.AddField(
            model_name='cases',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon'),
        ),
    ]
