# Generated by Django 2.0.4 on 2018-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20171114_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
