# Generated by Django 2.0.4 on 2018-07-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_auto_20180703_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='status',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='type',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='type',
            field=models.CharField(max_length=48),
        ),
    ]
