# Generated by Django 2.0.4 on 2018-07-03 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20180703_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='last_modified_user',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='leverancier',
        ),
        migrations.AlterField(
            model_name='contract',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contractbij_Klant', to='crm.Bedrijf'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_bij',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contractbij_Leverancier', to='crm.Bedrijf'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='klantpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Klantpartner', to=settings.AUTH_USER_MODEL, verbose_name='Contracteigenaar'),
        ),
        migrations.DeleteModel(
            name='SLA',
        ),
    ]
