# Generated by Django 2.0.4 on 2018-07-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_auto_20180703_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='projectcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projecten.Verkoopkans'),
        ),
    ]
