# Generated by Django 2.0.4 on 2018-07-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_auto_20180703_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leverancier',
            name='last_modified_user',
        ),
        migrations.DeleteModel(
            name='Leverancier',
        ),
    ]
