# Generated by Django 2.0.4 on 2018-07-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20180703_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytype',
            old_name='type',
            new_name='ActivityType',
        ),
    ]
