# Generated by Django 2.0.4 on 2018-07-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_auto_20180703_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytype',
            old_name='ActivityType',
            new_name='activiteit_type',
        ),
    ]
