# Generated by Django 2.0.4 on 2018-07-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_auto_20180703_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetype',
            old_name='type',
            new_name='case_type',
        ),
    ]
