# Generated by Django 2.0.4 on 2018-07-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_auto_20180703_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.CaseType'),
        ),
    ]
