# Generated by Django 2.0.4 on 2019-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_cases_case_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiteiten',
            options={'verbose_name': 'Activiteit', 'verbose_name_plural': 'Activiteiten'},
        ),
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'verbose_name': 'Activiteit status', 'verbose_name_plural': 'Activiteit statussen'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'Activiteit type', 'verbose_name_plural': 'Activiteit typen'},
        ),
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
