# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projecten', '0007_auto_20171207_1504'),
        ('crm', '0007_auto_20171207_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('onderwerp', models.CharField(max_length=80)),
                ('notitie', models.CharField(max_length=512, null=True)),
                ('datumtijd', models.DateTimeField(default=datetime.datetime.now)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf')),
                ('contactpersoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contactpersoon')),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('verkoopkans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projecten.Verkoopkans')),
            ],
            options={
                'verbose_name_plural': 'Notities',
            },
        ),
    ]
