# Generated by Django 2.0.4 on 2018-06-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotitieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('notitietype', models.CharField(max_length=30, unique=True)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name_plural': 'Notitietypen',
                'ordering': ['notitietype'],
            },
        ),
        migrations.AddField(
            model_name='notitie',
            name='notitietype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notities.NotitieType'),
        ),
    ]
