# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170930_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branche',
            options={'ordering': ['branch'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='contactpersoon',
            name='nieuwsbrief',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactpersoon',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
