# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20171002_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpersoon',
            name='onenote',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
