# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contactpersoon_onenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpersoon',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
    ]
