# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171108_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='Land',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
