# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_auto_20171207_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatietype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('relatietype', models.CharField(max_length=80, unique=True)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name_plural': 'Relatietypen',
                'ordering': ['relatietype'],
            },
        ),
        migrations.AlterField(
            model_name='contactpersoon',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='titel'),
        ),
        migrations.AddField(
            model_name='bedrijf',
            name='relatietype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Relatietype'),
        ),
    ]
