# Generated by Django 2.0.4 on 2018-06-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0008_auto_20180423_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpersoon',
            name='klantpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Relatiemanager', to=settings.AUTH_USER_MODEL, verbose_name='Relatiemanager'),
        ),
        migrations.AlterField(
            model_name='bedrijf',
            name='klantpartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Klantpartner', to=settings.AUTH_USER_MODEL, verbose_name='Relatiemanager'),
        ),
    ]
