# Generated by Django 2.0.4 on 2019-06-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180606_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijf',
            name='branche',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, to='crm.Branche'),
            preserve_default=False,
        ),
    ]
