# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCNaam', models.CharField(max_length=40, unique=True)),
                ('Gebruiker', models.CharField(max_length=80)),
                ('MerkenType', models.CharField(max_length=80)),
                ('Kenmerken', models.TextField()),
                ('Aanschafdatum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Software', models.CharField(max_length=80)),
                ('Versienummer', models.CharField(max_length=20)),
                ('Productkey', models.CharField(max_length=40)),
                ('PCNaam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcoverzicht.Computers')),
            ],
            options={
                'verbose_name_plural': 'Software',
            },
        ),
    ]
