# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['naam'], 'verbose_name_plural': 'Computers'},
        ),
        migrations.AlterField(
            model_name='software',
            name='productkey',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
