# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name_plural': 'Computers'},
        ),
    ]
