# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0002_auto_20170124_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='Serienummer',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
