# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0003_computer_serienummer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='Aanschafdatum',
            new_name='aanschafdatum',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Gebruiker',
            new_name='gebruiker',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Kenmerken',
            new_name='menmerken',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='MerkenType',
            new_name='merkenType',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='PCNaam',
            new_name='naam',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Serienummer',
            new_name='serienummer',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='PCNaam',
            new_name='naam',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='Productkey',
            new_name='productkey',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='Software',
            new_name='software',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='Versienummer',
            new_name='versienummer',
        ),
    ]
