# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0004_auto_20170124_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='menmerken',
            new_name='kenmerken',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='merkenType',
            new_name='merkentype',
        ),
    ]
