# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0006_auto_20170124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serienummer',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='software',
            name='productkey',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
