# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcoverzicht', '0007_auto_20170124_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='naam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcoverzicht.Computer', verbose_name='PC Naam'),
        ),
    ]
