# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_auto_20171207_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productgroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('productcode', models.CharField(max_length=10, unique=True)),
                ('omschrijving', models.CharField(max_length=80, unique=True)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('leverancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Bedrijf')),
                ('productowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productowner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productgroepen',
                'ordering': ['productcode'],
            },
        ),
    ]
