# Generated by Django 2.0.4 on 2018-06-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_dt', models.DateTimeField(auto_now=True, null=True)),
                ('omschrijving', models.CharField(max_length=80, unique=True)),
                ('last_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
                ('productgroep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producten.Productgroep')),
            ],
            options={
                'verbose_name_plural': 'Trainingen',
                'ordering': ['omschrijving'],
            },
        ),
    ]
