# Generated by Django 2.0.4 on 2019-12-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0002_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('omschrijving', models.CharField(max_length=80, unique=True)),
                ('prijs_per_eenheid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eenheid', models.CharField(choices=[('S', 'Stuksprijs'), ('U', 'Uurprijs'), ('D', 'Dagprijs')], max_length=1)),
                ('productgroep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producten.Productgroep')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producten',
            },
        ),
    ]
